[build]
  publish = "/"

[[redirects]]
  from = "/pilgrim"
  to = "/pilgrim.html"
  status = 200

[[redirects]]
  from = "/driver"
  to = "/driver.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
